openapi: 3.0.1
info:
  title: DemoAPI
  description: API Definition of DemoAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/demo
paths:
  /:
    get:
      responses:
        default:
          description: Default response
